# Generated by Django 3.2 on 2021-12-17 13:00

import cms.models.fields
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cms', '0022_auto_20180620_1551'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Committee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='contact email')),
                ('show_members', models.BooleanField(default=True, verbose_name='show members')),
                ('active', models.BooleanField(default=True, verbose_name='Still active')),
                ('name_en', models.CharField(max_length=255, verbose_name='name (EN)')),
                ('name_nl', models.CharField(max_length=255, verbose_name='name (NL)')),
                ('description', cms.models.fields.PlaceholderField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, slotname='description', to='cms.placeholder', verbose_name='description')),
                ('image', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.FILER_IMAGE_MODEL, verbose_name='image')),
            ],
        ),
        migrations.CreateModel(
            name='CommitteeMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('since', models.DateField(default=datetime.date.today, verbose_name='member since')),
                ('until', models.DateField(blank=True, null=True, verbose_name='member until')),
                ('chair', models.BooleanField(default=False, verbose_name='chair of committee')),
                ('committee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='committees.committee', verbose_name='committee')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
        migrations.AddField(
            model_name='committee',
            name='members',
            field=models.ManyToManyField(through='committees.CommitteeMembership', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='committee',
            name='permissions',
            field=models.ManyToManyField(to='auth.Permission'),
        ),
    ]
