# Generated by Django 3.2 on 2021-12-17 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('committees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='committee',
            name='permissions',
            field=models.ManyToManyField(blank=True, to='auth.Permission'),
        ),
    ]
