# Generated by Django 3.2 on 2021-12-17 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('committees', '0002_alter_committee_permissions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='committee',
            name='permissions',
        ),
        migrations.AddField(
            model_name='committee',
            name='perm_group',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.PROTECT, to='auth.group'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='committee',
            name='active',
            field=models.BooleanField(default=True, verbose_name='active committee'),
        ),
    ]
