# Generated by Django 3.2 on 2021-12-23 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('committees', '0004_alter_committee_perm_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='committee',
            name='perm_group',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='auth.group', verbose_name='Permissions'),
        ),
    ]
