# Generated by Django 4.0 on 2023-01-02 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('committees', '0005_alter_committee_perm_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='committee',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='is staff on the site'),
        ),
    ]
