# Generated by Django 4.0 on 2023-01-25 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('committees', '0006_committee_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='committee',
            name='show_in_achievements',
            field=models.BooleanField(default=True, verbose_name='Show committee in personal achievements'),
        ),
    ]
