# Generated by Django 3.0.9 on 2020-08-28 13:00

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birthday', models.DateField()),
                ('phone_number', models.CharField(max_length=16)),
                ('street_address', models.CharField(max_length=255, verbose_name='Street address and house number')),
                ('postcode', models.CharField(max_length=7, validators=[django.core.validators.RegexValidator('^\\d{4} ?[A-Za-z]{2}$')])),
                ('city', models.CharField(max_length=52)),
                ('is_student', models.BooleanField()),
                ('sports_card_number', models.CharField(max_length=10)),
                ('graduation_date', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
