# Generated by Django 3.0.9 on 2020-12-21 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='student_type',
            field=models.CharField(blank=True, choices=[('RU', 'radboud universiteit'), ('HAN', 'hogeschool Arnhem Nijmegen')], max_length=3),
        ),
    ]
