# Generated by Django 3.0.9 on 2020-12-21 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_member_student_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='student_type',
            field=models.CharField(blank=True, choices=[('RU', 'radboud university'), ('HAN', 'HAN')], max_length=3, null=True),
        ),
    ]
