# Generated by Django 3.0.9 on 2021-02-09 19:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_auto_20201221_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='birthday',
            field=models.DateField(verbose_name='birthday'),
        ),
        migrations.AlterField(
            model_name='member',
            name='city',
            field=models.CharField(max_length=52, verbose_name='city'),
        ),
        migrations.AlterField(
            model_name='member',
            name='graduation_date',
            field=models.DateField(verbose_name='graduation date'),
        ),
        migrations.AlterField(
            model_name='member',
            name='is_student',
            field=models.BooleanField(verbose_name='is student'),
        ),
        migrations.AlterField(
            model_name='member',
            name='phone_number',
            field=models.CharField(max_length=16, verbose_name='phone number'),
        ),
        migrations.AlterField(
            model_name='member',
            name='postcode',
            field=models.CharField(max_length=7, validators=[django.core.validators.RegexValidator('^\\d{4} ?[A-Za-z]{2}$')], verbose_name='postcode'),
        ),
        migrations.AlterField(
            model_name='member',
            name='sports_card_number',
            field=models.CharField(max_length=10, verbose_name='sports card number'),
        ),
        migrations.AlterField(
            model_name='member',
            name='student_type',
            field=models.CharField(blank=True, choices=[('RU', 'radboud university'), ('HAN', 'HAN')], max_length=3, null=True, verbose_name='student type'),
        ),
    ]
