# Generated by Django 3.0.9 on 2021-02-24 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_auto_20210209_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='street_address',
            field=models.CharField(max_length=255, verbose_name='street name and house number'),
        ),
    ]
