# Generated by Django 3.0.9 on 2021-03-02 20:45

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('members', '0004_auto_20210209_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='postcode',
            field=models.CharField(max_length=7, validators=[django.core.validators.RegexValidator('^\\d{4} ?[A-Za-z]{2}$')], verbose_name='zipcode'),
        ),
        migrations.AlterField(
            model_name='member',
            name='street_address',
            field=models.CharField(max_length=255, verbose_name='street name and house number'),
        ),
        migrations.AlterField(
            model_name='member',
            name='student_type',
            field=models.CharField(blank=True, choices=[('RU', 'radboud university'), ('HAN', 'HAN')], max_length=3, null=True, verbose_name='institution'),
        ),
        migrations.AlterField(
            model_name='member',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
