# Generated by Django 3.0.9 on 2021-02-24 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_member_other_club'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherClub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='other club')),
            ],
        ),
        migrations.AlterField(
            model_name='member',
            name='other_club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='members.OtherClub', verbose_name='other club'),
        ),
    ]
