# Generated by Django 3.0.9 on 2021-02-24 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_auto_20210224_2056'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='otherclub',
            options={'ordering': ('name',)},
        ),
        migrations.RemoveField(
            model_name='member',
            name='is_student',
        ),
        migrations.AlterField(
            model_name='member',
            name='student_type',
            field=models.CharField(blank=True, choices=[('RU', 'Radboud University'), ('HAN', 'HAN')], max_length=3, null=True, verbose_name='student type'),
        ),
    ]
