# Generated by Django 3.0.9 on 2021-02-24 21:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0010_auto_20210224_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='postcode',
            field=models.CharField(max_length=7, validators=[django.core.validators.RegexValidator('^\\d{4} ?[A-Za-z]{2}$')], verbose_name='zipcode'),
        ),
        migrations.AlterField(
            model_name='member',
            name='student_type',
            field=models.CharField(choices=[('RU', 'Radboud University'), ('HAN', 'HAN'), ('NS', 'Not a student')], max_length=3, verbose_name='institution'),
        ),
    ]
