# Generated by Django 3.0.9 on 2021-03-02 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0011_auto_20210224_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otherclub',
            name='name',
            field=models.CharField(max_length=64, unique=True, verbose_name='other club'),
        ),
    ]
