# Generated by Django 3.0.9 on 2021-03-02 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_auto_20210302_2045'),
        ('members', '0012_auto_20210302_2014'),
    ]

    operations = [
    ]
