# Generated by Django 3.0.9 on 2021-03-09 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0013_merge_20210302_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='student_type',
            field=models.CharField(choices=[('RU', 'Radboud University'), ('HAN', 'HAN'), ('NS', 'Not a student')], default='RU', max_length=3, verbose_name='institution'),
            preserve_default=False,
        ),
    ]
