# Generated by Django 3.0.9 on 2021-03-20 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0013_merge_20210302_2218'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='preferred_language',
            field=models.CharField(choices=[('en', 'English'), ('nl', 'Dutch')], default='nl', max_length=3),
        ),
        migrations.AlterField(
            model_name='member',
            name='student_type',
            field=models.CharField(choices=[('RU', 'Radboud University'), ('HAN', 'HAN'), ('NS', 'Not a student')], default='NS', max_length=3, verbose_name='institution'),
            preserve_default=False,
        ),
    ]
