# Generated by Django 3.0.9 on 2021-03-09 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0014_auto_20210309_2133'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'permissions': (('can_accept_or_reject', 'can accept or reject'),)},
        ),
    ]
