# Generated by Django 3.1.7 on 2021-03-30 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0014_auto_20210320_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='student_type',
            field=models.CharField(choices=[('RU', 'Radboud University'), ('HAN', 'HAN'), ('NS', 'Not a student')], max_length=3),
        ),
    ]
