# Generated by Django 3.0.9 on 2021-03-25 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0015_auto_20210309_2234'),
        ('members', '0014_auto_20210320_1059'),
    ]

    operations = [
    ]
