# Generated by Django 3.1.7 on 2021-04-02 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0016_merge_20210325_2053'),
        ('members', '0015_auto_20210330_1823'),
    ]

    operations = [
    ]
