# Generated by Django 3.1.7 on 2021-04-20 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0017_merge_20210402_1335'),
        ('members', '0017_merge_20210402_1333'),
    ]

    operations = [
    ]
