# Generated by Django 3.1.7 on 2021-04-20 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0017_merge_20210402_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='gender',
            field=models.CharField(default='Unspecified', max_length=64, verbose_name='gender'),
            preserve_default=False,
        ),
    ]
