# Generated by Django 3.2 on 2021-06-24 13:33

from django.db import migrations, models
import django.db.models.deletion
import filer.fields.file


class Migration(migrations.Migration):

    dependencies = [
        ('filer', '0012_file_mime_type'),
        ('members', '0018_merge_20210420_1321'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivacyFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', filer.fields.file.FilerFileField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='filer.file')),
            ],
        ),
    ]
