# Generated by Django 3.2 on 2021-06-24 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filer', '0012_file_mime_type'),
        ('members', '0019_privacyfile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PrivacyFile',
            new_name='MemberSettings',
        ),
    ]
