# Generated by Django 3.2 on 2021-06-24 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0020_rename_privacyfile_membersettings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='membersettings',
            old_name='file',
            new_name='privacyFile',
        ),
    ]
