# Generated by Django 3.2 on 2021-06-24 15:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0020_auto_20210624_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='postcode',
            field=models.CharField(max_length=64, validators=[django.core.validators.RegexValidator(code='invalid_postcode', message='postcode can only contain spaces, digits and letters', regex='^[\\s\\da-zA-Z]+$')], verbose_name='zipcode'),
        ),
        migrations.AlterField(
            model_name='member',
            name='sports_card_number',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(code='invalid_sports_card_number', message='sports card number has invalid form', regex='^[sueSUE]?\\d{6,8}$')], verbose_name='sports card number'),
        ),
    ]
