# Generated by Django 3.2 on 2021-06-24 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0021_auto_20210624_1515'),
        ('members', '0021_rename_file_membersettings_privacyfile'),
    ]

    operations = [
    ]
