# Generated by Django 3.2 on 2021-07-09 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0022_merge_20210624_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='picture_publication_acceptation',
            field=models.BooleanField(),
        ),
    ]
