# Generated by Django 3.2 on 2021-07-09 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0023_alter_member_picture_publication_acceptation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='other_club',
            field=models.BooleanField(default=False, verbose_name='other club'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='OtherClub',
        ),
    ]
