# Generated by Django 3.2 on 2021-08-02 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0023_auto_20210701_1243'),
    ]

    operations = [
    ]
