# Generated by Django 3.2 on 2021-08-11 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0024_auto_20210709_1447'),
        ('members', '0024_auto_20210809_1118'),
    ]

    operations = [
    ]
