# Generated by Django 3.1.7 on 2021-08-11 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0024_merge_20210802_1043'),
    ]

    operations = [
    ]
