# Generated by Django 3.1.7 on 2021-08-11 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0025_merge_0024_auto_20210709_1447_0024_auto_20210809_1118'),
        ('members', '0025_merge_20210811_1415'),
    ]

    operations = [
    ]
