# Generated by Django 3.2 on 2021-08-22 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0028_remove_member_picture_publication_acceptation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='graduation_date',
        ),
    ]
