# Generated by Django 3.2 on 2021-08-22 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0029_remove_member_graduation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='remarks',
            field=models.TextField(blank=True, null=True, verbose_name='remarks'),
        ),
    ]
