# Generated by Django 3.2 on 2021-08-22 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0030_member_remarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='student_type',
            field=models.CharField(choices=[('RU', 'Radboud University'), ('HAN', 'HAN'), ('NS', 'Not a student')], max_length=3, verbose_name='Where do you study?'),
        ),
    ]
