# Generated by Django 3.2 on 2021-08-22 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0028_auto_20210822_1148'),
        ('members', '0031_alter_member_student_type'),
    ]

    operations = [
    ]
