# Generated by Django 3.2 on 2021-08-22 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0032_merge_20210822_1635'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='graduation_date',
        ),
    ]
