# Generated by Django 4.0 on 2022-12-20 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0033_auto_20211223_2149'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='display_name',
            field=models.CharField(choices=[('Firstname', 'first name'), ('Fullname', 'full name'), ('Initials', 'initial with last name'), ('Nickname', 'nickname'), ('FullnameNickname', 'full name with nickname')], default='Firstname', max_length=64, verbose_name='display name'),
        ),
        migrations.AddField(
            model_name='member',
            name='nickname',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='nickname'),
        ),
        migrations.AlterField(
            model_name='member',
            name='bio',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='bio'),
        ),
    ]
