# Generated by Django 4.0 on 2022-12-20 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0034_member_display_name_member_nickname_alter_member_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='display_name',
            field=models.CharField(choices=[('Firstname', 'First name'), ('Fullname', 'Full name'), ('Initials', 'Initial with last name'), ('Nickname', 'Nickname'), ('FullnameNickname', 'Full name with nickname'), ('FullnameNickname', 'First name with nickname')], default='Firstname', max_length=64, verbose_name='display name'),
        ),
    ]
