# Generated by Django 4.0 on 2022-12-20 23:44

from django.db import migrations, models
import members.models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0036_alter_member_display_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=members.models.user_directory_path),
        ),
    ]
