# Generated by Django 4.0 on 2023-04-19 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0039_alter_member_display_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='google_email',
            field=models.EmailField(max_length=254, verbose_name='google email address'),
        ),
    ]
