# Generated by Django 4.2.5 on 2023-11-01 15:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0040_alter_member_google_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="sports_card_number",
            field=models.CharField(
                max_length=10,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid_sports_card_number",
                        message="sports card number has invalid form",
                        regex="^\\d{6}$",
                    )
                ],
                verbose_name="Sport center customer number",
            ),
        ),
    ]
