# Generated by Django 3.0.9 on 2021-02-09 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_auto_20210209_1951'),
        ('boards', '0002_auto_20210130_1003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boardmembership',
            name='function',
        ),
        migrations.AddField(
            model_name='boardmembership',
            name='function_en',
            field=models.CharField(default='english function', max_length=255, verbose_name='function (EN)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='boardmembership',
            name='function_nl',
            field=models.CharField(default='nederlandse functie', max_length=255, verbose_name='function (NL)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='board',
            name='end',
            field=models.DateField(blank=True, null=True, verbose_name='end'),
        ),
        migrations.AlterField(
            model_name='board',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='picture'),
        ),
        migrations.AlterField(
            model_name='board',
            name='start',
            field=models.DateField(verbose_name='start'),
        ),
        migrations.AlterField(
            model_name='boardmembership',
            name='board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boards.Board', verbose_name='board'),
        ),
        migrations.AlterField(
            model_name='boardmembership',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='boardmembership',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='members.Member', verbose_name='member'),
        ),
        migrations.AlterField(
            model_name='boardmembership',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='boardmembership',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='picture'),
        ),
    ]
