# Generated by Django 3.0.9 on 2021-03-02 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0003_auto_20210209_1951'),
        ('boards', '0003_previousboardmodel'),
    ]

    operations = [
    ]
