# Generated by Django 3.2 on 2021-08-31 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0005_auto_20210831_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardmembership',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='board',
            name='end',
            field=models.DateField(verbose_name='end'),
        ),
    ]
