# Generated by Django 3.2 on 2021-09-01 11:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0005_auto_20210831_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardmembership',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='board',
            name='end',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='end'),
            preserve_default=False,
        ),
    ]
