# Generated by Django 3.2 on 2021-09-10 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0032_merge_20210822_1635'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='remarks')),
                ('member_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relation_1_set', to='members.member', verbose_name='member 1')),
                ('member_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relation_2_set', to='members.member', verbose_name='member 2')),
            ],
            options={
                'unique_together': {('member_1', 'member_2')},
            },
        ),
    ]
