# Generated by Django 3.2 on 2021-09-01 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slideshow',
            name='image_description',
            field=models.TextField(verbose_name='description'),
        ),
    ]
