# Generated by Django 3.0.9 on 2021-02-09 19:51

import cms.models.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cms', '0022_auto_20180620_1551'),
        ('events', '0003_auto_20200901_2005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='name',
        ),
        migrations.AddField(
            model_name='event',
            name='name_en',
            field=models.CharField(default='name eng', max_length=255, verbose_name='name (EN)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='name_nl',
            field=models.CharField(default='naam nl', max_length=255, verbose_name='name (NL)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='cost',
            field=models.IntegerField(blank=True, null=True, verbose_name='cost'),
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=cms.models.fields.PlaceholderField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, slotname='description', to='cms.Placeholder', verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(max_length=255, verbose_name='location'),
        ),
        migrations.AlterField(
            model_name='event',
            name='registration_end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='registration end'),
        ),
        migrations.AlterField(
            model_name='event',
            name='registration_start',
            field=models.DateTimeField(blank=True, null=True, verbose_name='registration start'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='registration date'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Event', verbose_name='event'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='has_payed',
            field=models.BooleanField(blank=True, null=True, verbose_name='has payed'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
    ]
