# Generated by Django 3.0.9 on 2021-03-02 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20210209_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='has_payed',
            field=models.BooleanField(blank=True, null=True, verbose_name='has paid'),
        ),
    ]
