# Generated by Django 3.2 on 2021-10-19 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_alter_event_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='private_registrations',
            field=models.BooleanField(default=False, verbose_name="Don't show who is registered"),
        ),
    ]
