# Generated by Django 3.2 on 2021-09-17 10:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_alter_event_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='form_link',
            field=models.CharField(blank=True, max_length=128, null=True, validators=[django.core.validators.RegexValidator(message='Please enter a google form share link', regex='https:\\/\\/docs\\.google\\.com\\/forms\\/d\\/e\\/[\\w\\d_]*\\/viewform\\?')], verbose_name='Google form link'),
        ),
    ]
