# Generated by Django 3.2 on 2021-10-19 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_alter_event_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end_date',
            field=models.DateTimeField(default=-2021, verbose_name='end date'),
            preserve_default=False,
        ),
    ]
