# Generated by Django 3.2 on 2021-11-30 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_event_form_link'),
        ('events', '0011_event_show_end_date'),
    ]

    operations = [
    ]
