# Generated by Django 3.2 on 2022-11-23 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_alter_event_form_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='cost',
            field=models.CharField(default=1, max_length=255, verbose_name='cost'),
            preserve_default=False,
        ),
    ]
