# Generated by Django 3.2 on 2022-11-23 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_alter_event_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='cost',
            field=models.CharField(max_length=255, null=True, verbose_name='cost'),
        ),
    ]
