# Generated by Django 4.2.23 on 2025-10-18 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0014_remove_event_cost_event_cost_en_event_cost_nl"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="description",
        ),
    ]
