# Generated by Django 4.2.23 on 2026-06-23 13:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0015_remove_event_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="form_link",
            field=models.CharField(
                blank=True,
                max_length=256,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Please enter a google form share link",
                        regex="https:\\/\\/docs\\.google\\.com\\/forms\\/d\\/e\\/[\\w\\d_-]*\\/viewform\\?",
                    )
                ],
                verbose_name="Google form link",
            ),
        ),
    ]
