# Generated by Django 3.2 on 2022-11-23 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0016_auto_20221123_1545'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='cost_en',
        ),
        migrations.RemoveField(
            model_name='event',
            name='cost_nl',
        ),
        migrations.AddField(
            model_name='event',
            name='cost',
            field=models.CharField(max_length=255, null=True, verbose_name='cost'),
        ),
        migrations.AlterField(
            model_name='event',
            name='name_en',
            field=models.CharField(default=0, max_length=255, verbose_name='name (EN)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='name_nl',
            field=models.CharField(default=0, max_length=255, verbose_name='name (NL)'),
            preserve_default=False,
        ),
    ]
