# Generated by Django 3.2 on 2022-11-23 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0017_auto_20221123_1553'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='cost',
        ),
        migrations.AddField(
            model_name='event',
            name='cost_en',
            field=models.CharField(max_length=255, null=True, verbose_name='cost (EN)'),
        ),
        migrations.AddField(
            model_name='event',
            name='cost_nl',
            field=models.CharField(max_length=255, null=True, verbose_name='cost (NL)'),
        ),
    ]
